// Common JS, every file in NODE is module (by default)
// Modules - Encapsulated Code (only share minimum)
const names = require("./4-names")
const sayHi = require("./5-utils")
const data = require("./6-alternative-flawor")

require("./7-mind-grenade")
//sayHi(names.jon)
//sayHi(names.pet)
//sayHi("suz")
